#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/src/bootstrap.php';


use App\Command\Generator;
use Symfony\Component\Console\Application;

$app = new Application('RedisGenerator', 1.0);
$app->add(new Generator());

$app->run();
